AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Strapi RDS MySQL database'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: The database instance type
  DBName:
    Type: String
    Default: strapi
    Description: The name of the database
  DBUsername:
    Type: String
    Description: Username for the database
  DBPassword:
    Type: String
    NoEcho: true
    Description: Password for the database

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Strapi RDS MySQL
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: mysql8.0
      Description: Parameter group for Strapi MySQL database
      Parameters:
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub strapi-mysql-${Environment}
      Engine: mysql
      EngineVersion: 8.0
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      StorageType: gp2
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBParameterGroupName: !Ref DBParameterGroup
      PubliclyAccessible: true
      BackupRetentionPeriod: 7
      MultiAZ: false
      AutoMinorVersionUpgrade: true
      DeletionProtection: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DBEndpoint:
    Description: The connection endpoint for the database
    Value: !GetAtt DBInstance.Endpoint.Address
  DBPort:
    Description: The port number on which the database accepts connections
    Value: !GetAtt DBInstance.Endpoint.Port
  DBName:
    Description: The name of the database
    Value: !Ref DBName
  DBSecurityGroupId:
    Description: The ID of the security group used by the database
    Value: !Ref DBSecurityGroup